[package]
name = "whisper-rs-sys"
version = "0.3.0"
edition = "2021"
description = "Rust bindings for whisper.cpp (FFI bindings)"
license = "Unlicense"
documentation = "https://docs.rs/whisper-rs-sys"
repository = "https://github.com/tazz4843/whisper-rs"
links = "whisper"
exclude = [
    "whisper.cpp/bindings",
    "whisper.cpp/examples",
    "whisper.cpp/extra",
    "whisper.cpp/models",
    "whisper.cpp/samples",
    "whisper.cpp/tests",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.64"
